export const ANSWERS = [
  "It is certain.",
  "It is decidedly so.",
  "Without a doubt.",
  "Yes definitely.",
  "You may rely on it.",
  "As I see it, yes.",
  "Most likely.",
  "Outlook good.",
  "Yes.",
  "Signs point to yes.",
  "Reply hazy, try again.",
  "Ask again later.",
  "Better not tell you now.",
  "Cannot predict now.",
  "Concentrate and try again.",
  "Don't count on it.",
  "My reply is no.",
  "My sources say no.",
  "Outlook not so good.",
  "Very doubtful.",
  "I can't say.",
  "I shall not say.",
  "I can't tell.",
  "Repeat question.",
  "I can not tell.",
  "I can not say.",
  "It is unclear",
  "Try again.",
  "I can't tell you.",
  "Let's see.",
  "Yes yes yes yes.",
  "Is decidedly so.",
  "Probably so",
  "Probaby yes",
  "Definitely so",
  "Definitely yes",
  "Assertedly so",
  "A possibility",
  "I can see that",
  "Good chance",
  "Great chance",
  "It is probable",
  "Assertedly yes",
  "It is possible",
  "The stars say so",
  "I hope so",
  "Of course",
  "It is possible",
  "No doubt",
  "Possibly so",
  "Definite Chance",
  "uh-huh",
  "Fair chance",
  "Sounds good",
  "I'll bet on it",
  "No",
  "No No No No No",
  "Decidedly not",
  "Probably no",
  "Probably not",
  "Definitely no",
  "Definitely not",
  "I doubt it",
  "No chance",
  "I don't see that",
  "Barely probable",
  "Not a chance",
  "Little chance",
  "Unfortunately no",
  "The stars say no",
  "Absolutely not",
  "Of course not",
  "tiny chance",
  "fat chance",
  "possibly not",
  "NOPE",
  "Not on sunday",
  "No possibility",
  "Slight chance",
  "I bet against it",
  "Unclear",
];
